baseurl = "https://stchlk.rbind.io/"
languageCode = "en-us"
title = "Kevin Stachelek"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "Extras"
    url = "/extras/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/whtns"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/stchlk"

[params]
    description = "The Personal Blog of Kevin Stachelek."
    dateFormat = "2006/01/02"
    customCSS = ["css/custom.css"]
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "protein_dye_logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

