---
title: "Twitter Favorites" 
author: Kevin Stachelek
date: '2019-01-01'
slug: curate-tweets
categories: []
tags: []
---

This is a dashboard of twitter favorites that I added in here after seeing it on [Joseph Stachelek's](https://jsta.rbind.io/) blog. A clue to what I'm interested in lately!


```{r, echo = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(rtweet)
library(magrittr)
library(dplyr)
library(DT)
library(widgetframe)
```


```{r}
user_name <- "stchlk"
my_likes  <- get_favorites(user_name, n = 100) %>% 
  select("created_at", "screen_name", "text", "urls_expanded_url") %>%
  arrange(desc(created_at))
```

```{r}
my_likes$created_at <- strptime(as.POSIXct(my_likes$created_at), 
                                format = "%Y-%m-%d")
my_likes$created_at <- format(my_likes$created_at, "%Y-%m-%d")
```

```{r}
createLink <- function(x) {
  if(is.na(x)){
    return("")
  }else{
    sprintf(paste0('<a href="', URLdecode(x),'" target="_blank">', 
                   substr(x, 1, 25) ,'</a>'))
  }
}

my_likes$urls_expanded_url <- lapply(my_likes$urls_expanded_url, 
                                     function(x) sapply(x, createLink))


```

```{r}
my_table <- datatable(my_likes, 
                      options = list(scrollX = TRUE, autoWidth = TRUE,
                                     columnDefs = list(list(
                                           width = '70%', 
                                           targets = c(2)))), 
                      rownames = FALSE,
                      fillContainer = TRUE,
                      width = "100%", 
                      colnames = c("Date", "Handle", "Text", "URL"))

my_table <- formatStyle(my_table, columns = 1:4, fontSize = '70%')
my_table <- formatStyle(my_table, columns = 3, width = '500px')
```


```{r}
frameWidget(my_table, width = "100%", height = 800, 
            options = frameOptions(allowfullscreen = TRUE))
```


